Refactored smart home, homework1.
glushenkovIG/smart-home-2019 pull request #1
Opened 2019-03-07 21:20 UTC by glushenkovIG

Sorry for breaking the deadline, I was surprised with complexity of a github manipulations in this case.

2019-03-08 14:16 UTC, iagoshkov requested changes
Переделайте в соответствии с замечаниями.
Уберите из git .class файлы, все что генерируется во время сборки проекта не должно жить в системе контроля версий, в ней храним только исходный код.

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      private static SensorEvent getNextSensorEvent() {
Нарушение SRP.
Генерация событий умного дома - отдельная responsibility должна жить в отдельном классе.

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/EventHandler.java
> +    void HandleEvent(SmartHome smartHome, Object event_, EventSender sender);
EventSender нужен не везде - это разбирали на занятии. Те handler-ы кому он нужен должны получать его через зависимость в конструкторе. Иначе все потребности всех handler-ов нам придется добавлять как параметры в метод handle.
+ в java принято методы с маленькой буквы называть

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/EventSender.java
> +public interface EventSender {
Почему EventSender?
CommandSender

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/EventSender.java
> +    Object sendCommand(Object o);
Зачем возвращается Object?

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/DoorSensorEventHandler.java
> +                        if (room.getName().equals("hall")) {
Проигрывание сценариев умного дома - это отдельная responsibility, как мы и обсуждали на занятии, нужно ее вынести в отдельный класс (отдельный eventhandler).
Иначе при добавлении новых сценариев нам придется каждый раз менять код этого класса и встраивать новые if-ы и циклы.

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/SensorEventHandler.java
> +    public void HandleEvent(SmartHome smartHome, Object event_, EventSender sender) {
Здесь тоже OCP нарушается. Каждый раз когда мы будем добавлять новые eventHandler-ы нам придется менять этот код и встраивать новые вызовы в if-ы которые тут уже есть увеличивая вероятность что-то тут поломать.

2019-03-08 14:16 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome/SmartHomeReader.java
> +    SmartHome Read(Object data);
Что за параметр Object?
Избавьтесь от него, принимайте все нужные типизированные параметры в конкретных реализациях через конструктор, а метод read оставьте без параметров.

2019-03-10 06:47 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/SensorEventHandler.java
> +    public void HandleEvent(SmartHome smartHome, Object event_, EventSender sender) {
Так, я правильно понял что нужно проходиться циклом по всем SensorEventTypes и в случае совпадения вызывать *SensorEventHandler? Таким образом мы сможем расширить функционал класса изменив лишь SensorEventTypes и запилив ещё один *SensorEventHandler, но не меняя source code. Если да то через что это лучше делать, через reflection?

2019-03-10 06:51 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/SensorEventHandler.java
> +    public void HandleEvent(SmartHome smartHome, Object event_, EventSender sender) {
Собственно вопроса два, как вызывать функцию с определённым именем и как передавать туда нужное кол-во полей, у нас же не всегда все три нужны. Может как-то можно передавать права на обращение к полям в качестве параметра?

2019-03-10 08:49 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/SensorEventHandler.java
> +    public void HandleEvent(SmartHome smartHome, Object event_, EventSender sender) {
Никакого reflection. Нужно сделать как мы делали на занятии.
В классе Application создать все XXXEventHandler-ы, сложить их в коллекцию.
При получении события проходиться по всем handler-ам и вызывать у каждого метод handle. А уже каждый handler внутри метода будет решать, хочет обработать переданное ему событие или просто его игнорирует.

2019-03-12 10:04 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/EventSender.java
> +public interface EventSender {
Согласен.

2019-03-12 10:05 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/EventSender.java
> +    Object sendCommand(Object o);
Согласен, а принимать Object, это верно вроде.

2019-03-12 10:06 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/EventHandler.java
> +    void HandleEvent(SmartHome smartHome, Object event_, EventSender sender);
Я помнил, забыл что конструкторы существуют(

2019-03-12 10:38 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/SensorEventHandler.java
> +    public void HandleEvent(SmartHome smartHome, Object event_, EventSender sender) {
Это было сложно, но я кажется понял, нам не нужен SensorEventHandler (пока по крайней мере)

2019-03-12 11:01 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/SmartHome/SmartHomeReader.java
> +    SmartHome Read(Object data);
А если я захочу несколько раз считать разные дома одним и тем же ридером?

2019-03-12 14:56 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/DoorSensorEventHandler.java
> +                        if (room.getName().equals("hall")) {
Done.

2019-03-12 14:56 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      private static SensorEvent getNextSensorEvent() {
Done.

2019-03-18 15:27 UTC, glushenkovIG commented
Want reopen for the second homework

2019-03-18 18:11 UTC, iagoshkov requested changes
Внешние итераторы нам не нужны.
А внутренний у вас не получился, перечитайте еще раз статью и вспомните что мы разбирали на занятии. Если остались вопросы - пишите в телеграм.

2019-03-18 18:11 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +            switch (action.getType()){
Это у вас не итератор получился.
Смысл итератора в том, что мы в нем заключаем логику обхода.
А само действие может быть любым и передается снаружи (как раз в виде Action. точнее в виде реализации интерфейса Action).
У вас же теперь Door нарушает OCP - для любых новых действий над дверью придется добавлять новые case-ы в этот switch statement.
Здесь нужно просто вызывать Action.apply(this) (ну, точнее, Action.execute).
А сам action уже будет решать какое именно действие с дверью ему нужно произвести (открыть/закрыть/заблокировать или еще что-то).

2019-03-18 18:11 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Light.java
> +            switch (action.getType()){
здесь тоже самое что и в Door - нарушен OCP

2019-03-19 13:17 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +            switch (action.getType()){
Fixed.

2019-03-19 13:17 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Light.java
> +            switch (action.getType()){
Fixed

2019-03-28 05:10 UTC, glushenkovIG commented
I want to reopen it later

2019-04-02 20:24 UTC, iagoshkov requested changes
С адаптером более менее норм, но мы в классе разбирали вашу домашку.
По старым ДЗ есть вопросы - посмотрите.
Ну и тестов нет на Alarm.

2019-04-02 20:24 UTC, sbt-agoshkov commented on UnitTests/ru/sbt/mipt/oop/Alarm/ActivatedAlarmStateTest.java
> +        Assert.assertEquals(1, 1);
Ну и как? Сработало?

2019-04-02 20:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Alarm/AlarmState.java
> +    abstract void activate();
тут вообще то пароль нужно передавать в метод как параметр

2019-04-02 20:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Alarm/AlarmState.java
> +    abstract void deActivate();
и тут пароль

2019-04-02 20:24 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/HallEventHandler.java
> +                    if (light.getId().equals(lightIterator.next().getId())) {
Это зачем такая странная логика и проверка?
Что с чем сравниваем и зачем?

2019-04-14 13:21 UTC, glushenkovIG commented on UnitTests/ru/sbt/mipt/oop/Alarm/ActivatedAlarmStateTest.java
> +        Assert.assertEquals(1, 1);
Написал в AlarmHendlerTest.

2019-04-14 13:47 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Event/SensorEvent/HallEventHandler.java
> +                    if (light.getId().equals(lightIterator.next().getId())) {
Это выключение света во всём доме когда входная дверь закрылась. Думаете лучше просто сгенерировать кучу эвентов вида LIGHT_OFF а как себя тогда поведёт сигнализация?

2019-04-17 05:33 UTC, glushenkovIG commented on src/main/java/ru/sbt/mipt/oop/Alarm/AlarmState.java
> +    abstract void activate();
Added.

2019-04-17 05:34 UTC, merged